routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth routes
Route::get('login','AuthController@showLoginForm')->name('auth.login');
Route::post('login','AuthController@login')->name('auth.login');
Route::get('logout','AuthController@logout')->name('auth.logout');

Route::middleware(['auth'])->group(function () {
  Route::get('/', function () {
      return view('home');
  })->name('home');

  Route::get('agenda', 'AgendaController@show')->name('agenda.show');
  Route::resource('interviews', 'InterviewController', ['only' => ['edit', 'update']]);
  Route::post('interviews/export/ical', 'InterviewController@exportIcal')->name('interviews.export.ical');
  Route::post('interviews/export/gcalendar', 'GCalendarController@export')->name('interviews.export.gcalendar');

  Route::group(['prefix' => 'gcalendar', 'as' => 'gcalendar.'], function () {
      Route::get('oauth2', 'GCalendarController@show')->name('show');
      Route::get('oauth2callback', 'GCalendarController@store')->name('oauth2callback');
      Route::get('refresh_token', 'GCalendarController@refreshToken')->name('refresh_token');
      Route::get('revoke_token', 'GCalendarController@revokeToken')->name('revoke_token');
  });

  Route::get('me', function () {
      return view('me');
  })->name('auth.show');
  Route::put('me', 'AuthController@update')->name('auth.update');

  // Require admin
  Route::middleware(['checkAdmin'])->group(function () {
      Route::resource('candidates', 'CandidateController')->except(['show']);
      Route::post('candidates/import', 'CandidateController@import')->name('candidates.import');

      Route::resource('interviews', 'InterviewController', ['except' => ['edit', 'update']]);
      Route::post('interviews/import', 'InterviewController@import')->name('interviews.import');
  });
});

resources/views/agenda.blade.php
@extends('layouts.app')

@section('title')
    Agenda
@endsection

@push('css')
  <link rel="stylesheet" type="text/css" href="{{ asset('fullcalendar/core/main.css?v='.config('app.version')) }}"/>
  <link rel="stylesheet" type="text/css" href="{{ asset('fullcalendar/daygrid/main.css?v='.config('app.version')) }}"/>
  <link rel="stylesheet" type="text/css" href="{{ asset('fullcalendar/bootstrap/main.css?v='.config('app.version')) }}"/>
  <link href='https://use.fontawesome.com/releases/v5.0.6/css/all.css' rel='stylesheet'>
@endpush

@section('content')
  <div class="container">
    <div id='calendar'></div>
    @include('includes.session-message')
    @include('interview.modal')
  </div>

  @push('js')
    <!-- FullCalendar -->
    <script src="{{asset('fullcalendar/core/main.js?v='.config('app.version')) }}"></script>
    <script src="{{asset('fullcalendar/core/locales/fr-ch.js?v='.config('app.version')) }}"></script>
    <script src="{{asset('fullcalendar/daygrid/main.js?v='.config('app.version')) }}"></script>
    <script src="{{asset('fullcalendar/bootstrap/main.js?v='.config('app.version')) }}"></script>
    <script src="{{asset('js/long-press-event.js?v='.config('app.version'))}}"></script>
    <script>
      var events = {!! $interviews !!};
      var exportIcalURL = '{{route('interviews.export.ical')}}';
      var exportGCalendarURL = '{{route('interviews.export.gcalendar')}}';
    </script>
    <script src="{{asset('js/agenda.js')}}"></script>
  @endpush
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('title')
    Accueil
@endsection

@push('css')

@endpush

@section('content')

  <h1>Accueil</h1>
  <p>Bienvenue sur le système de entretiens d'admission de la section INF ! Cette application a été développée dans le cadre du projet TPI par Loïc Herzig.</p>

  @push('js')

  @endpush
@endsection

resources/views/me.blade.php
@extends('layouts.app')

@section('title')
    Mon compte
@endsection

@push('css')

@endpush

@section('content')

  <h1>{{Auth::user()->fullname()}} - {{Auth::user()->teaAcronym}}</h1>

  @include('includes.session-message')
  <form enctype="multipart/form-data" method="POST" action="{{ route('auth.update') }}">
    @method('PUT')
    {{ csrf_field() }}

    <div class="form-group">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">Nom d'utilisateur</span>
        </div>
        <input name="username" type="text" class="form-control" value="{{Auth::user()->teaUsername}}">
      </div>

      @if ($errors->has('username'))
        <div class="alert alert-danger" role="alert">
          {{ $errors->first('username') }}
        </div>
      @endif
    </div>

    <div class="form-group">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">Mot de passe</span>
        </div>
        <input name="password" type="password" class="form-control" value="">
      </div>

      @if ($errors->has('password'))
        <div class="alert alert-danger" role="alert">
          {{ $errors->first('password') }}
        </div>
      @endif
    </div>

    <div class="form-group">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">Adresse mail</span>
        </div>
        <input name="email" type="email" class="form-control" value="{{Auth::user()->teaEmail}}">
      </div>

      @if ($errors->has('email'))
        <div class="alert alert-danger" role="alert">
          {{ $errors->first('email') }}
        </div>
      @endif
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-primary">
        Modifier
      </button>

      @if (!Auth::user()->teaGCAccessToken)
        <a href="{{route('gcalendar.show')}}" class="btn btn-secondary">Associer Google Calendar</a>
      @else
        <a href="{{route('gcalendar.revoke_token')}}" class="btn btn-secondary">Dissocier Google Calendar</a>
      @endif
    </div>

  </form>

  @push('js')

  @endpush
@endsection