routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth routes
Route::get('login','AuthController@showLoginForm')->name('auth.login');
Route::post('login','AuthController@login')->name('auth.login');
Route::get('logout','AuthController@logout')->name('auth.logout');

Route::middleware(['auth'])->group(function () {
  Route::get('/', function () {
      return view('home');
  })->name('home');

  Route::get('agenda', 'AgendaController@show')->name('agenda.show');
  Route::resource('interviews', 'InterviewController', ['only' => ['edit', 'update']]);
  Route::post('interviews/export/ical', 'InterviewController@exportIcal')->name('interviews.export.ical');
  Route::post('interviews/export/gcalendar', 'GCalendarController@export')->name('interviews.export.gcalendar');

  Route::group(['prefix' => 'gcalendar', 'as' => 'gcalendar.'], function () {
      Route::get('oauth2', 'GCalendarController@show')->name('show');
      Route::get('oauth2callback', 'GCalendarController@store')->name('oauth2callback');
      Route::get('refresh_token', 'GCalendarController@refreshToken')->name('refresh_token');
      Route::get('revoke_token', 'GCalendarController@revokeToken')->name('revoke_token');
  });

  Route::get('me', function () {
      return view('me');
  })->name('auth.show');
  Route::put('me', 'AuthController@update')->name('auth.update');

  // Require admin
  Route::middleware(['checkAdmin'])->group(function () {
      Route::resource('candidates', 'CandidateController')->except(['show']);
      Route::post('candidates/import', 'CandidateController@import')->name('candidates.import');

      Route::resource('interviews', 'InterviewController', ['except' => ['edit', 'update']]);
      Route::post('interviews/import', 'InterviewController@import')->name('interviews.import');
  });
});

app/Models/Candidate.php
<?php
/// ETML
/// Author: Loïc Herzig
/// Date: 06.05.2019
/// Description: Model for teachers

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Candidate extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'idCandidate', 'canNo', 'canFirstname', 'canLastname'
    ];

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 't_candidate';

    /**
     * The primary key for the model.
     *
     * @var string
     */
    protected $primaryKey = 'idCandidate';

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = true;

    /**
     * Indicates if the timestamps are saved.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The deleted at timestamp for the model.
     *
     * @var string
     */
    const DELETED_AT = 'canDeletedAt';

    /**
     * Override parent boot and Call deleting event
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::deleting(function($candidate) {
           foreach ($candidate->interviews()->get() as $interview) {
              $interview->delete();
           }
        });
    }

    /**
     * The interviews that the candidate has
     *
     * By default ordered by interview's start descending
     *
     * @return array of Interview
     */
    public function interviews() {
        return $this->hasMany(Interview::class, 'fkCandidate')->orderBy('intStart','desc');
    }

    /**
    * The formation that choose the candidate.
    *
    * @return Formation
    */
    public function formation() {
        return $this->belongsTo(Formation::class, 'fkFormation', 'idFormation');
    }

    /**
     * Get formated firstname and lastname ('firstname lastname')
     * @return string full name
     */
    public function fullname(){
        return $this->canFirstname.' '.$this->canLastname;
    }
}

app/Http/Controllers/CandidateController.php
<?php
/**
  * ETML
  * Author: Loïc Herzig
  * Date: 09.05.2019
  */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Validator;
use PhpOffice\PhpSpreadsheet\IOFactory;
use App\Models\Candidate;
use App\Models\Formation;

/**
 * Candidate's controller class
 */
class CandidateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('candidate.index', ['candidates' => Candidate::orderBy('canNo')->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('candidate.form', [
            'action' => 'add',
            'formations' => Formation::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'no' => 'required|integer',
            'firstname' => 'required|string|max:255',
            'lastname' => 'required|string|max:255',
            'formation' => 'required|numeric',
        ]);

        // Check if formation exist
        $formation = Formation::findOrFail($request->formation);

        // Create
        $candidate = new Candidate();
        $candidate->canNo = $request->no;
        $candidate->canFirstname = $request->firstname;
        $candidate->canLastname = $request->lastname;
        $candidate->formation()->associate($formation);
        $candidate->save();

        $request->session()->flash('message', ['result' => true, 'title' => __('gest.addSucces.title'), 'msg' => __('gest.addSucces.msg', ['model' => $candidate->fullname()])]);
        return redirect()->route('candidates.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Candidate  $candidate
     * @return \Illuminate\Http\Response
     */
    public function edit(Candidate $candidate)
    {
        return view('candidate.form', [
            'action' => 'edit',
            'candidate' => $candidate,
            'formations' => Formation::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Candidate  $candidate
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Candidate $candidate)
    {
        $validatedData = $request->validate([
            'no' => 'required|integer',
            'firstname' => 'required|string|max:255',
            'lastname' => 'required|string|max:255',
            'formation' => 'required|numeric',
        ]);

        // Check if formation exist
        $formation = Formation::findOrFail($request->formation);

        // Create
        $candidate->canNo = $request->no;
        $candidate->canFirstname = $request->firstname;
        $candidate->canLastname = $request->lastname;
        $candidate->formation()->associate($formation);
        $candidate->save();

        $request->session()->flash('message', ['result' => true, 'title' => __('gest.editSucces.title'), 'msg' => __('gest.editSucces.msg', ['model' => $candidate->fullname()])]);
        return redirect()->route('candidates.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Candidate  $candidate
     * @return \Illuminate\Http\Response
     */
    public function destroy(Candidate $candidate)
    {
        $candidate->delete();
    }

    /**
     * Import candidates by reading excel file (xls, xlsx, xlsm)
     * @param  Request $request
     * @return Redirect
     */
    public function import(Request $request)
    {
        $validatedData = $request->validate([
            'file' => 'required|file|mimes:xls,xlsx,xlsm'
        ]);

        // Get file from request
        $file = $request->file('file');

        // Load file and sheet with datas
        $spreadsheet = IOFactory::load($file);
        $worksheetName = config('import.candidates.sheet_name');
        $worksheet = $spreadsheet->getSheetByName($worksheetName);

        if (!$worksheet){
            $request->session()->flash('message', ['result' => false, 'title' => __('gest.sheetNotFound.title'), 'msg' => __('gest.sheetNotFound.msg', ['name' => $worksheetName])]);
            return redirect()->route('candidates.index');
        }

        $rowIterator = $worksheet->getRowIterator(config('import.candidates.header_row'));
        $cellIteratorHeader = $rowIterator->current()->getCellIterator();

        $noHeader = config('import.candidates.header_no');
        $firstnameHeader = config('import.candidates.header_firstname');
        $lastnameHeader = config('import.candidates.header_lastname');
        $formationHeader = config('import.candidates.header_formation');
        foreach ($cellIteratorHeader as $cell) {
            switch ($cell->getFormattedValue()) {
                case $noHeader:
                    $noColumn = $cell->getColumn();
                    break;

                case $firstnameHeader:
                    $firstnameColumn = $cell->getColumn();
                    break;

                case $lastnameHeader:
                    $lastnameColumn = $cell->getColumn();
                    break;

                case $formationHeader:
                    $formationColumn = $cell->getColumn();
                    break;

                default:
                    // Nothing to do...
                    break;
            }
        }

        if (!isset($noColumn)){
            $request->session()->flash('message', ['result' => false, 'title' => __('gest.headerNoNotFound.title'), 'msg' => __('gest.headerNoNotFound.msg', ['header' => $noHeader])]);
            return redirect()->route('candidates.index');
        }
        if (!isset($firstnameColumn)){
            $request->session()->flash('message', ['result' => false, 'title' => __('gest.headerFirstnameNotFound.title'), 'msg' => __('gest.headerFirstnameNotFound.msg', ['header' => $firstnameHeader])]);
            return redirect()->route('candidates.index');
        }
        if (!isset($lastnameColumn)){
            $request->session()->flash('message', ['result' => false, 'title' => __('gest.headerLastnameNotFound.title'), 'msg' => __('gest.headerLastnameNotFound.msg', ['header' => $lastnameHeader])]);
            return redirect()->route('candidates.index');
        }
        if (!isset($formationColumn)){
            $request->session()->flash('message', ['result' => false, 'title' => __('gest.headerFormationNotFound.title'), 'msg' => __('gest.headerFormationNotFound.msg', ['header' => $formationHeader])]);
            return redirect()->route('candidates.index');
        }

        // Loop in rows and extract candidate data we want
        $candidateRow = config('import.candidates.header_row') + 1;
        if ($candidateRow > $worksheet->getHighestRow()){
            $request->session()->flash('message', ['result' => true, 'title' => __('gest.importCandidatesSucces.title'), 'msg' => __('gest.importCandidatesSucces.msg')]);
            return redirect()->route('candidates.index');
        }
        $rowIterator = $worksheet->getRowIterator($candidateRow);
        $candidates = [];
        foreach ($rowIterator as $row){
            $no = $worksheet->getCell($noColumn.$row->getRowIndex())->getFormattedValue();
            $firstname = mb_ucfirst(mb_strtolower($worksheet->getCell($firstnameColumn.$row->getRowIndex())->getFormattedValue()));
            $lastname = mb_ucfirst(mb_strtolower($worksheet->getCell($lastnameColumn.$row->getRowIndex())->getFormattedValue()));
            $formationCode = $worksheet->getCell($formationColumn.$row->getRowIndex())->getFormattedValue();
            $formation = Formation::where('forCode', $formationCode)->first();

            if (!$formation){
                $request->session()->flash('message', ['result' => false, 'title' => __('gest.formationNotExistWithCode.title'), 'msg' => __('gest.formationNotExistWithCode.msg', ['code' => $formationCode])]);
                return redirect()->route('candidates.index');
            }

            $candidates[] = [
                'no' => $no,
                'firstname' => $firstname,
                'lastname' => $lastname,
                'formation' => $formation
            ];
        }

        // Validate datas
        $validator = Validator::make($candidates, [
            '*' => 'array',
            '*.no'    => 'required|integer',
            '*.firstname'  => 'required|string',
            '*.lastname'  => 'required|string',
            '*.formation' => 'required'
        ]);

        if ($validator->fails()) {
            $request->session()->flash('message', ['result' => false, 'title' => __('gest.importDataInvalid.title'), 'msg' => __('gest.importDataInvalid.msg')]);
            return redirect()->route('candidates.index');
        }

        foreach ($candidates as $candidate){
            $_candidate = new Candidate();
            $_candidate->canNo = $candidate['no'];
            $_candidate->canFirstname = $candidate['firstname'];
            $_candidate->canLastname = $candidate['lastname'];
            $_candidate->formation()->associate($candidate['formation']);
            $_candidate->save();
        }

        $request->session()->flash('message', ['result' => true, 'title' => __('gest.importCandidatesSucces.title'), 'msg' => __('gest.importCandidatesSucces.msg')]);
        return redirect()->route('candidates.index');
    }
}

resources/views/candidate/data.blade.php
@foreach ($candidates as $candidate)
  <tr>
    <th scope="row">{{$candidate->idCandidate}}</th>
    <th>{{$candidate->canNo}}</th>
    <td>{{$candidate->canFirstname}}</td>
    <td>{{$candidate->canLastname}}</td>
    <td>{{$candidate->formation->forCode}} - {{$candidate->formation->forName}}</td>
    <td class="actions">
      <a class="remove-candidate" href="{{route('candidates.destroy', ['id' => $candidate->idCandidate])}}"><span class="glyphicon glyphicon-remove"></span></a>
      <a href="{{route('candidates.edit', ['id' => $candidate->idCandidate])}}"><span class="glyphicon glyphicon-edit"></span></a>
    </td>
  </tr>
@endforeach

resources/views/candidate/form.blade.php
@extends('layouts.app')

@section('title')
  @if ($action == 'edit')
    {{ $candidate->fullname() }} - Modification
  @elseif ($action == 'add')
    Ajouter un candidat
  @endif
@endsection

@push('css')

@endpush

@section('content')

  <h1>
    @if ($action == 'edit')
      {{ $candidate->fullname() }} - Modification
    @elseif ($action == 'add')
      <h2>Ajouter un candidat</h2>
    @endif
  </h1>

  @include('includes.session-message')

  <form enctype="multipart/form-data"
  @if ($action == 'edit')
    method="POST" action="{{ route('candidates.update', ['id' => $candidate->idCandidate]) }}"
  @elseif ($action == 'add')
    method="POST" action="{{ route('candidates.store') }}"
  @endif
  >
    @if ($action == 'edit') @method('PUT') @endif
    {{ csrf_field() }}

    <div class="form-group">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">N°</span>
        </div>
        <input required name="no" type="text" class="form-control" value="{{isset($candidate) ? $candidate->canNo : old('no')}}">
      </div>

      @if ($errors->has('no'))
        <div class="alert alert-danger" role="alert">
          {{ $errors->first('no') }}
        </div>
      @endif
    </div>

    <div class="form-group">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">Prénom</span>
        </div>
        <input required name="firstname" type="text" class="form-control" value="{{isset($candidate) ? $candidate->canFirstname : old('firstname')}}">
      </div>

      @if ($errors->has('firstname'))
        <div class="alert alert-danger" role="alert">
          {{ $errors->first('firstname') }}
        </div>
      @endif
    </div>

    <div class="form-group">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">Nom</span>
        </div>
        <input required name="lastname" type="text" class="form-control" value="{{isset($candidate) ? $candidate->canLastname : old('lastname')}}">
      </div>

      @if ($errors->has('lastname'))
        <div class="alert alert-danger" role="alert">
          {{ $errors->first('lastname') }}
        </div>
      @endif
    </div>

    <div class="form-group">
      <div class="input-group">
        <div class="input-group-prepend">
          <label class="input-group-text">Formation</label>
        </div>
        <select name="formation" class="bootstrap-select" required>
          <option disabled selected value> -- Choisissez une formation -- </option>
          @foreach ($formations as $formation)
            @if ((isset($candidate) && $candidate->formation == $formation) || old('formation') == $formation->idFormation)
              <option selected value="{{$formation->idFormation}}">{{$formation->forCode}} - {{$formation->forName}}</option>
            @else
              <option value="{{$formation->idFormation}}">{{$formation->forCode}} - {{$formation->forName}}</option>
            @endif
          @endforeach
        </select>
      </div>

        @if ($errors->has('formation'))
            <div class="alert alert-danger" role="alert">
              {{ $errors->first('formation') }}
            </div>
        @endif
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-primary">
        @if ($action == 'edit')
          Modifier
        @elseif ($action == 'add')
          Ajouter
        @endif
      </button>
    </div>

  </form>


  @push('js')

  @endpush
@endsection

resources/views/candidate/index.blade.php
@extends('layouts.app')

@section('title')
    Candidats
@endsection

@push('css')
  <link rel="stylesheet" type="text/css" href="{{ asset('css/datatables.min.css?v='.config('app.version')) }}"/>
@endpush

@section('content')

  <h1>Candidats</h1>

  @include('includes.session-message')

  <div class="mb-2">
    <form id="import-excel-file" action="{{route('candidates.import')}}" method="POST" enctype="multipart/form-data">
      {{ csrf_field() }}
      <div class="input-group">
        <div class="custom-file">
          <input type="file" class="custom-file-input" name="file">
          <label class="custom-file-label" for="inputGroupFile04">Choisir un fichier .xls, .xlsx ou .xlsm</label>
        </div>
        <div class="input-group-append">
          <button class="btn btn-outline-secondary" type="submit">Importer</button>
        </div>
      </div>
      @if ($errors->has('file'))
        <div class="alert alert-danger mt-1" role="alert">
          {{ $errors->first('file') }}
        </div>
      @endif
    </form>
  </div>

  <table id="table-candidates" class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">N°</th>
        <th scope="col">Prénom</th>
        <th scope="col">Nom</th>
        <th scope="col">Formation</th>
        <th class="actions" scope="col">
          Actions
          <a href="{{route('candidates.create')}}"><span class="glyphicon glyphicon-plus"></span></a>
        </th>
      </tr>
    </thead>
    <tbody id="candidates-container">
        @include('candidate.data')
    </tbody>
  </table>

  @push('js')
    <script type="text/javascript" src="{{ asset('js/datatables.min.js?v='.config('app.version')) }}"></script>
    <script type="text/javascript" src="{{ asset('js/candidate.js?v='.config('app.version')) }}"></script>
  @endpush
@endsection