routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth routes
Route::get('login','AuthController@showLoginForm')->name('auth.login');
Route::post('login','AuthController@login')->name('auth.login');
Route::get('logout','AuthController@logout')->name('auth.logout');

Route::middleware(['auth'])->group(function () {
  Route::get('/', function () {
      return view('home');
  })->name('home');

  Route::get('agenda', 'AgendaController@show')->name('agenda.show');
  Route::resource('interviews', 'InterviewController', ['only' => ['edit', 'update']]);
  Route::post('interviews/export/ical', 'InterviewController@exportIcal')->name('interviews.export.ical');
  Route::post('interviews/export/gcalendar', 'GCalendarController@export')->name('interviews.export.gcalendar');

  Route::group(['prefix' => 'gcalendar', 'as' => 'gcalendar.'], function () {
      Route::get('oauth2', 'GCalendarController@show')->name('show');
      Route::get('oauth2callback', 'GCalendarController@store')->name('oauth2callback');
      Route::get('refresh_token', 'GCalendarController@refreshToken')->name('refresh_token');
      Route::get('revoke_token', 'GCalendarController@revokeToken')->name('revoke_token');
  });

  Route::get('me', function () {
      return view('me');
  })->name('auth.show');
  Route::put('me', 'AuthController@update')->name('auth.update');

  // Require admin
  Route::middleware(['checkAdmin'])->group(function () {
      Route::resource('candidates', 'CandidateController')->except(['show']);
      Route::post('candidates/import', 'CandidateController@import')->name('candidates.import');

      Route::resource('interviews', 'InterviewController', ['except' => ['edit', 'update']]);
      Route::post('interviews/import', 'InterviewController@import')->name('interviews.import');
  });
});

app/Http/Controllers/InterviewController.php
<?php
/**
  * ETML
  * Author: Loïc Herzig
  * Date: 08.05.2019
  */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Validator;
use Auth;
use PhpOffice\PhpSpreadsheet\IOFactory;
use App\Models\Interview;
use App\Models\Decision;
use App\Models\Candidate;
use App\Models\Teacher;

use Mail;
use App\Mail\ExportICal;

use Eluceo\iCal\Component\Calendar;
use Eluceo\iCal\Component\Event;

use PhpOffice\PhpSpreadsheet\Shared\Date as DateExcel;

/**
 * Interview's controller class
 */
class InterviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('interview.index', [
          'interviews' => Interview::all(),
          'decisions' => Decision::all(),
          'candidates' => Candidate::all(),
          'teachers' => Teacher::expectAdmin()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('interview.form', [
          'action' => 'add',
          'decisions' => Decision::all(),
          'candidates' => Candidate::all(),
          'teachers' => Teacher::expectAdmin()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
          'start.date' => 'required|date|date_format:Y-m-d|after_or_equal:'.now()->format('d.m.Y'),
          'start.hour' => 'required|numeric|between:0,23',
          'start.minute' => 'required|numeric|between:0,59',
          'location' => 'nullable|string|max:50',
          'remark' => 'nullable|string',
          'points' => 'nullable|integer',
          'decision' => 'nullable|numeric',
          'candidate' => 'required|numeric',
          'teachers' => 'required|array|min:2',
          'teachers.*' => 'numeric'
        ]);

        $start = $request->start['date'].' '.sprintf("%02d", $request->start['hour']).':'.sprintf("%02d", $request->start['minute']);
        $startDateTime = \DateTime::createFromFormat('Y-m-d H:i', $start);

        $endDateTime = \DateTime::createFromFormat( 'Y-m-d H:i', $startDateTime->format('Y-m-d H:i') );
        $endDateTime->add(new \DateInterval('PT'.config('app.interview_length').'M'));

        // Check existence of teacher before save and map
        $teachers = collect($request->teachers)->map(function ($teacher){
            return Teacher::findOrFail($teacher);
        })->reject(function ($teacher) {
            return $teacher->teaUsername == 'admin';
        });

        // create
        $interview = new Interview();
        $interview->intStart = $startDateTime;
        $interview->intEnd = $endDateTime;
        $interview->intLocation = $request->location;
        $interview->intRemark = $request->remark;
        $interview->intPoints = $request->points;
        if ($request->decision){
            $interview->decision()->associate(Decision::findOrFail($request->decision));
        }
        $interview->candidate()->associate(Candidate::findOrFail($request->candidate));
        $interview->save();

        // Add teachers relation
        foreach ($teachers as $teacher){
            $interview->teachers()->attach($teacher);
        }

        $request->session()->flash('message', ['result' => true, 'title' => __('gest.addSucces.title'), 'msg' => __('gest.addSucces.msg', ['model' => $interview->candidate->fullname()])]);
        return redirect()->route('interviews.index');
    }

    /**
     * Display the specified resource in json if ajax or redirect in index view.
     *
     * @param  \App\Models\Interview  $interview
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Interview $interview)
    {
        // Return json formated interview for ajax
        if ($request->ajax()){
          return response()->json([
            'id' => $interview->idInterview,
            'start' => $interview->intStart->format('d.m.Y H:i'),
            'end' => $interview->intEnd->format('d.m.Y H:i'),
            'location' => $interview->intLocation,
            'remark' => $interview->intRemark,
            'points' => $interview->intPoints,
            'decision' => $interview->decision ? $interview->decision->decName : '',
            'candidate' => $interview->candidate->fullname(),
            'teachers' => $interview->teachers->map(function ($teacher) {return $teacher->fullname();})
          ]);
        } else {
          return redirect()->route('interviews.index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Interview  $interview
     * @return \Illuminate\Http\Response
     */
    public function edit(Interview $interview)
    {
        $data = [
          'action' => 'edit',
          'interview' => $interview,
          'decisions' => Decision::all()
        ];

        if (Auth::user()->teaIsAdmin){
          $data['candidates'] = Candidate::all();
          $data['teachers'] = Teacher::expectAdmin();
        }

        return view('interview.form', $data);
    }

    /**
     * Go to the update function according to user permission.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Interview  $interview
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Interview $interview)
    {
        if (Auth::user()->teaIsAdmin) { return Self::updateAdmin($request, $interview); }
        else { return Self::updateTeacher($request, $interview); }
    }

    /**
     * Update the specified resource in storage for admin.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Interview  $interview
     * @return \Illuminate\Http\Response
     */
    private function updateAdmin(Request $request, Interview $interview)
    {
        $rules = [
          'start.date' => 'required|date|date_format:Y-m-d',
          'start.hour' => 'required|numeric|between:0,23',
          'start.minute' => 'required|numeric|between:0,59',
          'location' => 'nullable|string|max:50',
          'remark' => 'nullable|string',
          'points' => 'nullable|integer',
          'decision' => 'nullable|numeric',
          'candidate' => 'required|numeric',
          'teachers' => 'required|array|min:2',
          'teachers.*' => 'numeric'
        ];

        // Check if end is after start
        $start = $request->start['date'].' '.$request->start['hour'].':'.$request->start['minute'];
        $startDateTime = \DateTime::createFromFormat('Y-m-d H:i', $start);

        $endDateTime = \DateTime::createFromFormat( 'Y-m-d H:i', $startDateTime->format('Y-m-d H:i') );
        $endDateTime->add(new \DateInterval('PT'.config('app.interview_length').'M'));

        // if date are different, it means we will change so I need to add validation on the moment
        if ($interview->intEnd->format('Y-m-d') != $request->start['date']){
          $rules['start.date'] = $rules['start.date'].'|after_or_equal:now';
        }

        $validatedData = $request->validate($rules);

        // Check existence of teacher before save and map
        $teachers = collect($request->teachers)->map(function ($teacher){
          return Teacher::findOrFail($teacher);
        })->reject(function ($teacher) {
          return $teacher->teaUsername == 'admin';
        });

        // update
        $interview->intStart = $startDateTime;
        $interview->intEnd = $endDateTime;
        $interview->intLocation = $request->location;
        $interview->intRemark = $request->remark;
        $interview->intPoints = $request->points;
        if ($request->decision){
          $interview->decision()->associate(Decision::findOrFail($request->decision));
        }
        $interview->candidate()->associate(Candidate::findOrFail($request->candidate));
        $interview->save();
        $interview->teachers()->sync($teachers->pluck('idTeacher'));

        $request->session()->flash('message', ['result' => true, 'title' => __('gest.editSucces.title'), 'msg' => __('gest.editSucces.msg', ['model' => $interview->candidate->fullname()])]);
        return redirect()->route('interviews.index');
    }

    /**
     * Update the specified resource in storage for teacher.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Interview  $interview
     * @return \Illuminate\Http\Response
     */
    private function updateTeacher(Request $request, Interview $interview)
    {
        $rules = [
          'remark' => 'nullable|string',
          'points' => 'nullable|integer',
          'decision' => 'nullable|numeric'
        ];

        $validatedData = $request->validate($rules);

        // update
        $interview->intRemark = $request->remark;
        $interview->intPoints = $request->points;
        if ($request->decision){
          $interview->decision()->associate(Decision::findOrFail($request->decision));
        }
        $interview->save();

        $request->session()->flash('message', ['result' => true, 'title' => __('gest.editSucces.title'), 'msg' => __('gest.editSucces.msg', ['model' => $interview->candidate->fullname()])]);
        return redirect()->route('agenda.show');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Interview  $interview
     * @return \Illuminate\Http\Response
     */
    public function destroy(Interview $interview)
    {
        $interview->delete();
    }

    /**
     * Import interviews by reading excel file (xls, xlsx, xlsm)
     * @param  Request $request
     * @return Redirect
     */
    public function import(Request $request)
    {

resources/views/interview/data.blade.php
@foreach ($interviews as $interview)
  <tr>
    <th scope="row">{{$interview->idInterview}}</th>
    <td>{{$interview->candidate->fullname()}}</td>
    <td>{{$interview->intStart->format('d.m.Y H:i')}}</td>
    <td>{{$interview->intLocation}}</td>
    <td>{{$interview->teachersAcronymsString()}}</td>
    <td class="actions">
      <a class="remove-interview" href="{{route('interviews.destroy', ['id' => $interview->idInterview])}}"><span class="glyphicon glyphicon-remove"></span></a>
      <a href="{{route('interviews.edit', ['id' => $interview->idInterview])}}"><span class="glyphicon glyphicon-edit"></span></a>
      <a class="show-interview" href="{{ route('interviews.show', ['id' => $interview->idInterview]) }}"><span class="glyphicon glyphicon-info-sign"></span></a>
    </td>
  </tr>
@endforeach

resources/views/interview/form.blade.php
@extends('layouts.app')

@section('title')
  @if ($action == 'edit')
    {{ $interview->idInterview }} - Modification
  @elseif ($action == 'add')
    Ajouter un entretien
  @endif
@endsection

@push('css')

@endpush

@section('content')

  <h1>
    @if ($action == 'edit')
      {{ $interview->idInterview }} - Modification
    @elseif ($action == 'add')
      <h2>Ajouter un entretien</h2>
    @endif
  </h1>

  @include('includes.session-message')

  <form enctype="multipart/form-data"
  @if ($action == 'edit')
    method="POST" action="{{ route('interviews.update', ['id' => $interview->idInterview]) }}"
  @elseif ($action == 'add')
    method="POST" action="{{ route('interviews.store') }}"
  @endif
  >
    @if ($action == 'edit') @method('PUT') @endif
    {{ csrf_field() }}

    @if (Auth::user()->teaIsAdmin)
      <div class="form-group">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">Date de début</span>
          </div>
          <input required name="start[date]" type="date" class="form-control" value="{{isset($interview) ? $interview->intStart->format('Y-m-d') : old('start.date')}}">
          <input required name="start[hour]" type="number" min="0" max="23" placeholder="Heure.." class="form-control" value="{{isset($interview) ? $interview->intStart->format('G') : old('start.hour')}}">
          <input required name="start[minute]" type="number" min="0" max="59" placeholder="Minute.." class="form-control" value="{{isset($interview) ? $interview->intStart->format('i') : old('start.minute')}}">
        </div>

        @if ($errors->has('start.date'))
          <div class="alert alert-danger" role="alert">
            {{ $errors->first('start.date') }}
          </div>
        @endif
        @if ($errors->has('start.hour'))
          <div class="alert alert-danger" role="alert">
            {{ $errors->first('start.hour') }}
          </div>
        @endif
        @if ($errors->has('start.minute'))
          <div class="alert alert-danger" role="alert">
            {{ $errors->first('start.minute') }}
          </div>
        @endif
      </div>

      <div class="form-group">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">Lieu</span>
          </div>
          <input name="location" type="text" class="form-control" value="{{isset($interview) ? $interview->intLocation : old('location')}}">
        </div>

        @if ($errors->has('location'))
          <div class="alert alert-danger" role="alert">
            {{ $errors->first('location') }}
          </div>
        @endif
      </div>
    @endif

    <div class="form-group">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">Remarque</span>
        </div>
        <textarea class="form-control" name="remark">{{isset($interview) ? $interview->intRemark : old('remark')}}</textarea>
      </div>

      @if ($errors->has('remark'))
        <div class="alert alert-danger" role="alert">
          {{ $errors->first('remark') }}
        </div>
      @endif
    </div>

    <div class="form-group">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">Points</span>
        </div>
        <input name="points" type="number" min="0" class="form-control" value="{{isset($interview) ? $interview->intPoints : old('points')}}">
      </div>

      @if ($errors->has('points'))
        <div class="alert alert-danger" role="alert">
          {{ $errors->first('points') }}
        </div>
      @endif
    </div>

    <div class="form-group {{ $errors->has('decision') ? ' has-error' : '' }}">
      <div class="input-group">
        <div class="input-group-prepend">
          <label class="input-group-text">Décison d'admission</label>
        </div>
        <select name="decision" class="bootstrap-select">
          <option selected value> -- Choisissez la décision -- </option>
          @foreach ($decisions as $decision)
            @if ((isset($interview) && $interview->decision == $decision) || old('decision') == $decision->idDecision)
              <option selected value="{{$decision->idDecision}}">{{$decision->decCode}} - {{$decision->decName}}</option>
            @else
              <option value="{{$decision->idDecision}}">{{$decision->decCode}} - {{$decision->decName}}</option>
            @endif
          @endforeach
        </select>
      </div>

        @if ($errors->has('decision'))
            <div class="alert alert-danger" role="alert">
              {{ $errors->first('decision') }}
            </div>
        @endif
    </div>

    @if (Auth::user()->teaIsAdmin)
      <div class="form-group {{ $errors->has('candidate') ? ' has-error' : '' }}">
        <div class="input-group">
          <div class="input-group-prepend">
            <label class="input-group-text">Candidat</label>
          </div>
          <select name="candidate" class="bootstrap-select" data-live-search="true" required>
            <option disabled selected value> -- Choisissez un candidat -- </option>
            @foreach ($candidates as $candidate)
              @if ((isset($interview) && $interview->candidate == $candidate) || old('candidate') == $candidate->idCandidate)
                <option selected value="{{$candidate->idCandidate}}">{{$candidate->fullname()}}</option>
              @else
                <option value="{{$candidate->idCandidate}}">{{$candidate->fullname()}}</option>
              @endif
            @endforeach
          </select>
        </div>

          @if ($errors->has('candidate'))
              <div class="alert alert-danger" role="alert">
                {{ $errors->first('candidate') }}
              </div>
          @endif
      </div>

      <div class="form-group {{ $errors->has('teachers') ? ' has-error' : '' }}">
        <div class="input-group">
          <div class="input-group-prepend">
            <label class="input-group-text">Enseignants</label>
          </div>
          <select size='5' multiple name="teachers[]" class="two-column-ms">
            @foreach ($teachers as $teacher)
              @if ((isset($interview) && $interview->teachers->contains($teacher)) || (!empty(old('teachers')) && in_array($teacher->idTeacher, old('teachers'))) )
                <option selected value="{{$teacher->idTeacher}}">{{$teacher->fullname()}}</option>
              @else
                <option value="{{$teacher->idTeacher}}">{{$teacher->fullname()}}</option>
              @endif
            @endforeach
          </select>
        </div>

        @if ($errors->has('teachers'))
            <div class="alert alert-danger" role="alert">
              {{ $errors->first('teachers') }}
            </div>
        @endif
      </div>
    @endif


    <div class="form-group">
      <button type="submit" class="btn btn-primary">
        @if ($action == 'edit')
          Modifier
        @elseif ($action == 'add')
          Ajouter
        @endif
      </button>
    </div>

  </form>


  @push('js')

  @endpush
@endsection

resources/views/interview/index.blade.php
@extends('layouts.app')

@section('title')
    Entretiens
@endsection

@push('css')
  <link rel="stylesheet" type="text/css" href="{{ asset('css/datatables.min.css?v='.config('app.version')) }}"/>
@endpush

@section('content')

  <h1>Entretiens</h1>

  @include('includes.session-message')

  <div class="mb-2">
    <form id="import-excel-file" action="{{route('interviews.import')}}" method="POST" enctype="multipart/form-data">
      {{ csrf_field() }}
      <div class="input-group">
        <div class="custom-file">
          <input type="file" class="custom-file-input" name="file">
          <label class="custom-file-label" for="inputGroupFile04">Choisir un fichier .xls, .xlsx ou .xlsm</label>
        </div>
        <div class="input-group-append">
          <button class="btn btn-outline-secondary" type="submit">Importer</button>
        </div>
      </div>
      @if ($errors->has('file'))
        <div class="alert alert-danger mt-1" role="alert">
          {{ $errors->first('file') }}
        </div>
      @endif
    </form>
  </div>

  <div class="form-inline" id="filters-interview">
    <!-- Candidates -->
    <select id="candidate-filter" multiple class="bootstrap-select filter-interview-input" title="Candidats..." data-live-search="true" data-actions-box="true">
      @foreach ($candidates as $candidate)
        <option>{{$candidate->fullname()}}</option>
      @endforeach
    </select>

    <!-- Teachers -->
    <select id="teacher-filter" multiple class="bootstrap-select filter-interview-input" title="Enseignants..." data-live-search="true" data-actions-box="true">
      @foreach ($teachers as $teacher)
        <option data-tokens="{{$teacher->teaAcronym}}">{{$teacher->teaAcronym}}</option>
      @endforeach
    </select>

    <input id="start-filter" type="text" class="form-control filter-interview-input" placeholder="Minimum..." onfocus="(this.type='date')" onblur="(this.type='text')">
    <input id="end-filter" type="text" class="form-control filter-interview-input" placeholder="Maximum..." onfocus="(this.type='date')" onblur="(this.type='text')">
    <input id="location-filter" type="text" class="form-control filter-interview-input" placeholder="Lieu...">
  </div>

  <table id="table-interviews" class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Candidat</th>
        <th scope="col">Date</th>
        <th scope="col">Lieu</th>
        <th scope="col">Enseignants</th>
        <th class="actions" scope="col">
          Actions
          <a href="{{route('interviews.create')}}"><span class="glyphicon glyphicon-plus"></span></a>
        </th>
      </tr>
    </thead>
    <tbody id="interviews-container">
        @include('interview.data')
    </tbody>
  </table>

  @include('interview.modal')

  @push('js')
    <script type="text/javascript" src="{{ asset('js/datatables.min.js?v='.config('app.version')) }}"></script>
    <script type="text/javascript" src="{{ asset('js/interview.js?v='.config('app.version')) }}"></script>
  @endpush
@endsection

resources/views/interview/modal.blade.php
<div class="modal" id="modal-interview">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title"><span id="modal-title"></span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
      </div>

      <div class="modal-body">
        <div class="clearfix"></div>
        <div class="infos_materiel">
          <div class="properties_box col-12">
            <!-- properties -->
            <div class="h4">Propriétés:</div>
            <div id="modal-properties">
              <p>Candidat: <span id="modal-candidate"></span></p>
              <p>Date: <span id="modal-date"></span></p>
              <p>Lieu: <span id="modal-location"></span></p>
              <p>Points: <span id="modal-points"></span></p>
              <p>Décision: <span id="modal-decision"></span></p>
            </div>

            <!-- Teachers -->
            <div class="h4">Enseignant(s):</div>
            <div id="modal-teachers">
              <ul>
                <!-- Insert <li> for one Brevet in js -->
              </ul>
          </div>

          <!-- Remark -->
          <div class="h4">Remarque:</div>
          <div>
            <p id="modal-remark"></p>
          </div>
        </div>
        <div class="clearfix"></div>
      </div>

      <div class="modal-footer">
        <a id="modal-edit-button" href="" class="btn btn-secondary">Modifier</a>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
      </div>

    </div>
  </div>
</div>